enableGlobalCache: true

enableTransparentWorkspaces: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.0.0-rc.39.git.20230216.hash-fb77381.cjs
